<?php

declare(strict_types=1);

namespace TradesMen\SecurityCenterConnector\Config;

/**
 * Canonical TradesMen Security Center connector environment variable names.
 *
 * The only supported env prefix is TRADESMEN_SECURITY_CENTER_*. Legacy TSC_*
 * and SECURITY_CENTER_* aliases are no longer read.
 *
 * Note: the X-TSC-* values are HTTP protocol headers, not env variables, and are
 * defined in {@see \TradesMen\SecurityCenterConnector\Protocol\Headers}. They are
 * unchanged by this env naming.
 *
 * This class only describes names. It never reads, prints, or logs any value.
 * Value resolution lives in {@see EnvResolver}.
 */
final class ConnectorEnvNames
{
    public const TRADESMEN_SECURITY_CENTER_CONNECTOR_ENABLED = 'TRADESMEN_SECURITY_CENTER_CONNECTOR_ENABLED';
    public const TRADESMEN_SECURITY_CENTER_CONNECTOR_MODE = 'TRADESMEN_SECURITY_CENTER_CONNECTOR_MODE';
    public const TRADESMEN_SECURITY_CENTER_APP_ID = 'TRADESMEN_SECURITY_CENTER_APP_ID';
    public const TRADESMEN_SECURITY_CENTER_INSTANCE = 'TRADESMEN_SECURITY_CENTER_INSTANCE';
    public const TRADESMEN_SECURITY_CENTER_ENVIRONMENT = 'TRADESMEN_SECURITY_CENTER_ENVIRONMENT';
    public const TRADESMEN_SECURITY_CENTER_ALLOWED_CLOCK_SKEW_SECONDS = 'TRADESMEN_SECURITY_CENTER_ALLOWED_CLOCK_SKEW_SECONDS';
    public const TRADESMEN_SECURITY_CENTER_NONCE_TTL_SECONDS = 'TRADESMEN_SECURITY_CENTER_NONCE_TTL_SECONDS';
    public const TRADESMEN_SECURITY_CENTER_KEY_ID = 'TRADESMEN_SECURITY_CENTER_KEY_ID';
    public const TRADESMEN_SECURITY_CENTER_SHARED_SECRET = 'TRADESMEN_SECURITY_CENTER_SHARED_SECRET';
    public const TRADESMEN_SECURITY_CENTER_SCOPES = 'TRADESMEN_SECURITY_CENTER_SCOPES';
    public const TRADESMEN_SECURITY_CENTER_ALLOWED_IPS = 'TRADESMEN_SECURITY_CENTER_ALLOWED_IPS';
    public const TRADESMEN_SECURITY_CENTER_REQUIRE_IP_ALLOWLIST = 'TRADESMEN_SECURITY_CENTER_REQUIRE_IP_ALLOWLIST';
    public const TRADESMEN_SECURITY_CENTER_URL = 'TRADESMEN_SECURITY_CENTER_URL';
    public const TRADESMEN_SECURITY_CENTER_HEARTBEAT_ENABLED = 'TRADESMEN_SECURITY_CENTER_HEARTBEAT_ENABLED';
    public const TRADESMEN_SECURITY_CENTER_HEARTBEAT_INTERVAL_SECONDS = 'TRADESMEN_SECURITY_CENTER_HEARTBEAT_INTERVAL_SECONDS';
    public const TRADESMEN_SECURITY_CENTER_HEARTBEAT_TIMEOUT_SECONDS = 'TRADESMEN_SECURITY_CENTER_HEARTBEAT_TIMEOUT_SECONDS';
    public const TRADESMEN_SECURITY_CENTER_CONNECTOR_TOKEN = 'TRADESMEN_SECURITY_CENTER_CONNECTOR_TOKEN';

    /**
     * Every canonical env name this package reads.
     *
     * @return list<string>
     */
    public static function canonicalNames(): array
    {
        return [
            self::TRADESMEN_SECURITY_CENTER_CONNECTOR_ENABLED,
            self::TRADESMEN_SECURITY_CENTER_CONNECTOR_MODE,
            self::TRADESMEN_SECURITY_CENTER_APP_ID,
            self::TRADESMEN_SECURITY_CENTER_INSTANCE,
            self::TRADESMEN_SECURITY_CENTER_ENVIRONMENT,
            self::TRADESMEN_SECURITY_CENTER_ALLOWED_CLOCK_SKEW_SECONDS,
            self::TRADESMEN_SECURITY_CENTER_NONCE_TTL_SECONDS,
            self::TRADESMEN_SECURITY_CENTER_KEY_ID,
            self::TRADESMEN_SECURITY_CENTER_SHARED_SECRET,
            self::TRADESMEN_SECURITY_CENTER_SCOPES,
            self::TRADESMEN_SECURITY_CENTER_ALLOWED_IPS,
            self::TRADESMEN_SECURITY_CENTER_REQUIRE_IP_ALLOWLIST,
            self::TRADESMEN_SECURITY_CENTER_URL,
            self::TRADESMEN_SECURITY_CENTER_HEARTBEAT_ENABLED,
            self::TRADESMEN_SECURITY_CENTER_HEARTBEAT_INTERVAL_SECONDS,
            self::TRADESMEN_SECURITY_CENTER_HEARTBEAT_TIMEOUT_SECONDS,
            self::TRADESMEN_SECURITY_CENTER_CONNECTOR_TOKEN,
        ];
    }
}
